FROM node:18

RUN mkdir /app
WORKDIR /app
RUN apt-get update

RUN npm install @kubernetes/client-node
RUN npm install -g selenium-side-runner
COPY .side.yml .side.yml

COPY runner.js runner.js

ENTRYPOINT ["/bin/sh", "-c" , "node runner.js"]
