apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: guestbook
spec:
  containers:
  - name: testpodcontainer
    image: quay.io/molnar_liviusz/selenium-test-runner:v0.0.1
    imagePullPolicy: Always
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  serviceAccountName: seleniumtest-sample