---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - selenium.selenium
  resources:
  - seleniumtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium.selenium
  resources:
  - seleniumtests/finalizers
  verbs:
  - update
- apiGroups:
  - selenium.selenium
  resources:
  - seleniumtests/status
  verbs:
  - get
  - patch
  - update
